name: LightningDeath
api: 4.0.0
authors:
  - provsalt
  - muqsit
version: 1.3.0
mcpe-protocol: [440, 448, 465]
src-namespace-prefix: provsalt\lightningdeath
main: provsalt\lightningdeath\Loader
permissions:
 lightningdeath.bypass:
    default: false
